# Initialization

## Cheetah 3
swing_time: 0.16
transition_time: 0.005
stance_time: 0.005

step_time_ratio: 1.0

body_height: .4

CTRL_move_to_target_height:
    max_rf_z: 350
    min_rf_z: 3

CTRL_fix_stance:

CTRL_frhl_swing:
    default_target_foot_location_1: [0.3, -0.17, 0.0] # Front Right
    default_target_foot_location_2: [-0.3, 0.17, 0.0] # Hind Left
    swing_height: 0.08
    landing_offset: [0, 0, 0]


CTRL_flhr_swing:
    default_target_foot_location_1: [0.3, 0.17, 0.0] # Front Left
    default_target_foot_location_2: [-0.3, -0.17, 0.0] # Hind Right
    swing_height: 0.08
    landing_offset: [0, 0, 0]

CTRL_two_leg_trans:
    max_rf_z: 350
    min_rf_z: 3


# Timing Parameters (sec)
body_lifting_time: 0.5

Kp: [ 300, 300, 300, 
      300, 300, 300, 
      300, 300, 300, 
      300, 300, 300 ]

Kd: [ 40., 40., 40., 
      40., 40., 40., 
      40., 40., 40., 
      40., 40., 40. ]

tau_lim: [-250., 250.]
