# Initialization

## Mini Cheetah
swing_time: 0.11
transition_time: 0.01
stance_time: 0.02

body_height: .25 
body_posture_Kp: [300, 300, 300, 100, 100, 300]
body_posture_Kd: [10, 10, 10, 20, 20, 10]


CTRL_move_to_target_height:
    max_rf_z: 100
    min_rf_z: 3

CTRL_fix_stance:

CTRL_frhl_swing:
    default_target_foot_location_1: [0.19, -0.11, 0.0] # Front Right
    default_target_foot_location_2: [-0.19, 0.11, 0.0] # Hind Left
    swing_height: 0.06
    landing_offset: [0, 0, 0]
    foot_Kp: [200, 200, 200]
    foot_Kd: [30, 30, 30]

CTRL_flhr_swing:
    default_target_foot_location_1: [0.19, 0.11, 0.0] # Front Left
    default_target_foot_location_2: [-0.19, -0.11, 0.0] # Hind Right
    swing_height: 0.06
    landing_offset: [0, 0, 0.00]
    foot_Kp: [200, 200, 200]
    foot_Kd: [30, 30, 30]
 
CTRL_two_leg_trans:
    max_rf_z: 100
    min_rf_z: 3


# Timing Parameters (sec)
body_lifting_time: 0.5


Kp: [ 100, 100, 100, 
      100, 100, 100, 
      100, 100, 100, 
      100, 100, 100 ]

Kd: [ 5., 5., 5., 
      5., 5., 5., 
      5., 5., 5., 
      5., 5., 5. ]

