# Initialization
#
## Mini Cheetah
#body_height: .25 #Mini cheetah

#CTRL_move_to_target_height:
    #max_rf_z: 50
    #min_rf_z: 3

#CTRL_fix_stance:

#CTRL_frhl_swing:
    #default_target_foot_location_1: [0.2, -0.12, 0.0] # Front Right
    #default_target_foot_location_2: [-0.2, 0.12, 0.0] # Hind Left
    #swing_height: 0.05
    #landing_offset: [0.025, 0., -0.0]

#CTRL_flhr_swing:
    #default_target_foot_location_1: [0.2, 0.12, 0.0] # Front Left
    #default_target_foot_location_2: [-0.2, -0.12, 0.0] # Hind Right
    #swing_height: 0.05
    #landing_offset: [0.025, 0., -0.0]

#CTRL_two_leg_trans:
    #max_rf_z: 60
    #min_rf_z: 3

## Cheetah 3
body_height: .4
CTRL_move_to_target_height:
    max_rf_z: 280
    min_rf_z: 3

CTRL_fix_stance:

CTRL_frhl_swing:
    default_target_foot_location_1: [0.25, -0.17, 0.0] # Front Right
    default_target_foot_location_2: [-0.25, 0.17, 0.0] # Hind Left
    swing_height: 0.2
    landing_offset: [0.0, 0, -0.0]

CTRL_flhr_swing:
    default_target_foot_location_1: [0.25, 0.17, 0.0] # Front Left
    default_target_foot_location_2: [-0.25, -0.17, 0.0] # Hind Right
    swing_height: 0.2
    landing_offset: [0.0, 0, -0.0]

CTRL_two_leg_trans:
    max_rf_z: 280
    min_rf_z: 3


# Optimization Info
max_num_step: 19 # optimizer's number of steps - 2
OPT_walking_forward:
    #folder_name: 2019-02-20-13_09_26
    #folder_name: 2019-02-20-11_11_36
    folder_name: saved_optimization_data/2019-03-05-00_00_03_2


# Timing Parameters (sec)
initial_stance_time: 1.0

## Experiment
swing_time: 0.16
transition_time: 0.005
stance_time: 0.03

Kp: [ 100, 100, 100, 
      100, 100, 100, 
      100, 100, 100, 
      100, 100, 100 ]

Kd: [ 5., 5., 5., 
      5., 5., 5., 
      5., 5., 5., 
      5., 5., 5. ]


