# Initialization

# Mini
body_height: 0.25

# Timing Parameters (sec)
body_lifting_time: 1.0
bounding_time: 10000.

CTRL_move_to_target_height:
    max_rf_z: 50
    min_rf_z: 3

CTRL_bounding_initiate:

CTRL_bounding:
    swing_time: 0.15
    default_stance_time: 0.1
    stride_length: 0.25

    Kp_ori: [50, 50, 50]
    Kd_ori: [3, 3, 3]
        
    Kp_leg_height: 50
    Kd_leg_height: 3

    Kp_xy_body: [0, 20]
    Kd_xy_body: [4, 2]
        
    Kd_foot: [30, 30, 30]
    Kd_foot: [3, 3, 3]


Kp_joint: [5.0, 5.0, 5.0]
Kd_joint: [0.5, 0.5, 0.5]


save_file: false
#save_file: true
