# Initialization

# Mini
body_height: 0.2
CTRL_move_to_target_height:
    max_rf_z: 50
    min_rf_z: 3

# Timing Parameters (sec)
body_lifting_time: 1.0
stance_time: 10000.

CTRL_stance:

Kp: [ 100, 100, 100, 
      100, 100, 100, 
      100, 100, 100, 
      100, 100, 100 ]

Kd: [ 5., 5., 5., 
      5., 5., 5., 
      5., 5., 5., 
      5., 5., 5. ]


