# Initialization

# Mini
body_height: 0.25
CTRL_move_to_target_height:
    max_rf_z: 50
    min_rf_z: 3

CTRL_backflip_pre:
    motion_type: "move_to_target"
    move_time: 2.0


# Timing Parameters (sec)
body_lifting_time: 1.0
stance_time: 10000.

CTRL_stance:

Kp: [ 100, 100, 100, 
      100, 100, 100, 
      100, 100, 100, 
      100, 100, 100 ]

Kd: [ 5., 5., 5., 
      5., 5., 5., 
      5., 5., 5., 
      5., 5., 5. ]

save_file: false
#save_file: true
