# Initialization

# Mini
body_height: 0.25

# Timing Parameters (sec)
body_lifting_time: 1.2
bounding_time: 10000.
#swing_time: 0.22
#default_stance_time: 0.13

swing_time: 0.18
default_stance_time: 0.15

leg_height: 0.28

CTRL_move_to_target_height:
  max_rf_z: 100
  min_rf_z: 3

CTRL_bounding_initiate:

CTRL_bounding:
  stride_length: 0.25
  K_time: 0.6
  front_foot_offset: 0.01
  hind_foot_offset: -0.04
  swing_height: 0.1
  front_jump_amp: 3.0
  hind_jump_amp: 8.5
  contact_vel_threshold: 2.5
  total_mass: 9.0
  step_length_limit: 0.3


# WBIC Feedback gain
Kp_ryrz: [5., 5.]
Kd_ryrz: [0.5, 0.5]

Kp_roll: 30
Kd_roll: 5
  
# Joint Feedback gain
Kp_joint: [13., 15., 15.]
Kd_joint: [1.5, 1.5, 1.5]
  
#Kp: [200., 200., 200., 
  #200., 200., 200., 
  #200., 200., 200., 
  #200., 200., 200.]

#Kd: [10., 10., 10., 
  #10., 10., 10., 
  #10., 10., 10., 
  #10., 10., 10.]

Kp: [130., 130., 130., 
  130., 130., 130., 
  130., 150., 150., 
  130., 150., 150.]

Kd: [6., 6., 6., 
  6., 6., 6., 
  6., 10., 10., 
  6., 10., 10.]

save_file: false
#save_file: true
