# Initialization

## Mini Cheetah
swing_time: 0.085
transition_time: 0.005
stance_time: 0.005

step_time_ratio: 0.7

body_height: .25
#body_height: .3
CTRL_move_to_target_height:
    max_rf_z: 100
    min_rf_z: 3

CTRL_fix_stance:

CTRL_frhl_swing:
    default_target_foot_location_1: [0.18, -0.1, 0.0] # Front Right
    default_target_foot_location_2: [-0.18, 0.1, 0.0] # Hind Left
    swing_height: 0.04
    landing_offset: [0, 0, 0.00]

CTRL_flhr_swing:
    default_target_foot_location_1: [0.18, 0.1,  0.0] # Front Left
    default_target_foot_location_2: [-0.18, -0.1, 0.0] # Hind Right
    swing_height: 0.04
    landing_offset: [0, 0, 0.00]

CTRL_two_leg_trans:
    max_rf_z: 100
    min_rf_z: 3

# Timing Parameters (sec)
body_lifting_time: 1.0


Kp: [ 200, 200, 200, 
      200, 200, 200, 
      200, 200, 200, 
      200, 200, 200 ]

Kd: [ 20., 20., 20., 
      20., 20., 20., 
      20., 20., 20., 
      20., 20., 20. ]

