# Initialization

# Mini
body_height: 0.25
CTRL_move_to_target_height:
    max_rf_z: 50
    min_rf_z: 3

# Timing Parameters (sec)
body_lifting_time: 1.0
stance_time: 10000.

CTRL_stance:

Kp: [ 30, 30, 30, 
      30, 30, 30, 
      30, 30, 30, 
      30, 30, 30 ]

Kd: [ 0.3, 0.3, 0.3, 
      0.3, 0.3, 0.3, 
      0.3, 0.3, 0.3, 
      0.3, 0.3, 0.3 ]

Kp_joint: [5.0, 5.0, 5.0]
Kd_joint: [0.5, 0.5, 0.5]


save_file: false
#save_file: true
