# Initialization

# Mini
body_height: 0.25
CTRL_move_to_target_height:
    max_rf_z: 50
    min_rf_z: 3

# Timing Parameters (sec)
body_lifting_time: 0.7
stance_time: 10000.

CTRL_stance:

Kp: [ 130, 130, 130, 
      130, 130, 130, 
      130, 130, 130, 
      130, 130, 130 ]

Kd: [ 2.0, 2.0, 2.0, 
      2.0, 2.0, 2.0, 
      2.0, 2.0, 2.0, 
      2.0, 2.0, 2.0 ]

Kp_joint: [5.0, 5.0, 5.0]
Kd_joint: [1.5, 1.5, 1.5]


save_file: false
#save_file: true
