# Initialization

## Mini Cheetah
swing_time: 0.2
transition_time: 0.02
stance_time: 0.02

body_height: .25 
#body_posture_Kp: [70, 70, 40, 100, 100, 100]
#body_posture_Kd: [3, 3, 3, 3, 3, 3]

body_posture_Kp: [400, 400, 400, 400, 400, 400]
body_posture_Kd: [10, 10, 10, 10, 10, 10]

CTRL_move_to_target_height:
    max_rf_z: 100
    min_rf_z: 0

CTRL_fix_stance:

CTRL_frhl_swing:
    default_target_foot_location_1: [0.18, -0.1, 0.0] # Front Right
    default_target_foot_location_2: [-0.18, 0.1, 0.0] # Hind Left
    swing_height: 0.05
    landing_offset: [0, 0, 0]
    #foot_Kp: [180, 180, 180]
    #foot_Kd: [7, 7, 7]
    foot_Kp: [200, 200, 200]
    foot_Kd: [30, 30, 30]


CTRL_flhr_swing:
    default_target_foot_location_1: [0.18, 0.1, 0.0] # Front Left
    default_target_foot_location_2: [-0.18, -0.1, 0.0] # Hind Right
    swing_height: 0.05
    landing_offset: [0, 0, 0.00]
    #foot_Kp: [180, 180, 180]
    #foot_Kd: [7, 7, 7]
    foot_Kp: [200, 200, 200]
    foot_Kd: [30, 30, 30]
 
CTRL_two_leg_trans:
    max_rf_z: 100
    min_rf_z: 0


# Timing Parameters (sec)
body_lifting_time: 1.5
save_file: false

Kp: [ 100, 100, 100, 
      100, 100, 100, 
      100, 100, 100, 
      100, 100, 100 ]

Kd: [ 5., 5., 5., 
      5., 5., 5., 
      5., 5., 5., 
      5., 5., 5. ]

Kp_joint: [0.0, 0.0, 0.0]
Kd_joint: [0.0, 0.0, 0.0]


