# Initialization

## Mini Cheetah
swing_time: 0.14
transition_time: 0.003
stance_time: 0.004
 
# Timing Parameters (sec)
body_lifting_time: .7


#swing_time: 0.12
#transition_time: 0.01
#stance_time: 0.01

step_time_ratio: 0.7

body_height: .25
#body_height: .3
CTRL_move_to_target_height:
    max_rf_z: 100
    min_rf_z: 0

CTRL_fix_stance:

CTRL_frhl_swing:
    default_target_foot_location_1: [0.18, -0.08, 0.0] # Front Right
    default_target_foot_location_2: [-0.18, 0.08, 0.0] # Hind Left
    swing_height: 0.04
    landing_offset: [0, 0, 0]

CTRL_flhr_swing:
    default_target_foot_location_1: [0.18, 0.08,  0.0] # Front Left
    default_target_foot_location_2: [-0.18, -0.08, 0.0] # Hind Right
    swing_height: 0.04
    landing_offset: [0, 0, 0]

CTRL_two_leg_trans:
    max_rf_z: 100
    min_rf_z: 0

#Kp_body_pos_kin: [0.5, 0.5, 1.0]
#Kp_body_ori_kin: [1.5, 1.5, 1.0]

Kp_body_pos_kin: [1.0, 1.0, 1.0]
Kp_body_ori_kin: [1.0, 1.0, 1.0]

## Low gain set
#Kp: [ 40, 40, 40, 
      #40, 40, 40, 
      #40, 40, 40, 
      #40, 40, 40 ]

#Kd: [ 0.5, 0.5, 0.5, 
      #0.5, 0.5, 0.5, 
      #0.5, 0.5, 0.5, 
      #0.5, 0.5, 0.5 ]

Kp_joint: [5.0, 5.0, 5.0]
Kd_joint: [1.5, 1.5, 1.5]

## High gain set
Kp: [ 80, 80, 80, 
      80, 80, 80, 
      80, 80, 80, 
      80, 80, 80 ]

Kd: [ 2., 2., 2., 
      2., 2., 2., 
      2., 2., 2., 
      2., 2., 2. ]
     
#Kp_joint: [25.0, 25.0, 25.0]
#Kd_joint: [1.5, 1.5, 1.5]

tau_lim: [-100., 100.]

#save_file: true
save_file: false
