# Generated on Mon Aug  5 18:20:08 2019
__collection-name__: user-parameters


Kd_joint          : [0.5, 0.5, 0.5]
#Kd_joint          : [0.8, 0.8, 0.8]
Kp_joint          : [4, 4, 4]
#Kp_joint          : [3, 3, 3]

Kp_body           : [30, 30, 30]
#Kp_body           : [3, 3, 3]
Kd_body           : [3, 3, 3]

#Kp_foot           : [100, 100, 100]
Kp_foot           : [70, 70, 70]
Kd_foot           : [3, 3, 3]

Kp_ori            : [30, 30, 30]
#Kp_ori            : [3, 3, 3]
Kd_ori            : [3, 3, 3]

cmpc_gait         : 9
cmpc_x_drag       : 0
cmpc_use_sparse   : 0
jcqp_alpha        : 1.5
jcqp_max_iter     : 10000
jcqp_rho          : 1e-07
jcqp_sigma        : 1e-08
jcqp_terminate    : 0.1
use_jcqp          : 0
use_wbc           : 1
