height_map_file: "2019-03-05-00_00_03/height_map.txt"
height_map_corner_origin: [0., -2.2, 0.0]

# [x, y, z, pitch, yaw] 
#robot_initial_posture: [0., 0., 0.4, 0.]
#robot_final_posture: [2.4, -0.0, 1.15, 0.]

robot_initial_posture: [0., 0., 0.4, 0.]
robot_final_posture: [1.2, -0.0, 0.4, 0.]

min_leg_length: 0.31
max_leg_length: 0.5
des_leg_length: 0.42

landing_loc_region: 0.12
landing_height_var: 0.00001
# Optimization Solver Settting
max_eval: 1000000
#max_eval: 1
max_time: 600 # (sec)

stair_terrain:
    num_stair: 5  # Must change final body height as the number of stair change
    x_start: 0.6
    y_start: 0.05

    width: 1.5
    #depth: 0.3
    depth: 0.07
    #height: 0.15
    height: 0.1
